apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dlrd6dgzs-nodejs 
  janus-idp.io/tekton: dlrd6dgzs-nodejs
  backstage.io/kubernetes-id: dlrd6dgzs-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dlrd6dgzs-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml